# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DPA7OQEM-ZBCZALnbHYeGpdfFHrT3CyU
"""

puppy = {
  "breed": "pug",
  "color": "white",
  "age": 1.5
}
x = puppy.setdefault("Owner_name", "Robert")


dict = puppy.items()

print(dict)

puppy.update({"Owner_name": "Robert"})

print(puppy)

x = puppy.get("age")

print(x)

puppy.clear()

print(puppy)

